windowrule = float on, match:class (^(Proton Pass)$|^(io.ente.auth)$|floating|scrcpy|gpartedbin|org.gnome.DiskUtility|com.example.cloudflare_warp_panel)
windowrule = center on, match:class (^(Proton Pass)$|^(io.ente.auth)$|floating)
windowrule = size 881 680, match:class ^(Proton Pass)$

windowrule = float on, match:initial_title ^(pairdrop.net_/)$
windowrule = size 787 503, match:initial_title ^(pairdrop.net_/)$
windowrule = center on, match:initial_title ^(pairdrop.net_/)$

windowrule = size 760 440, match:class (floating)

# windowrule = float on, match:class (btop)
# windowrule = size 875 675, match:class (btop) 
# windowrule = size 592 397, match:class (btop)
# windowrule = center on, match:class (btop)

windowrule = float on, match:initial_class (xdg-desktop-portal-gtk)
windowrule = size 760 440, match:initial_class (xdg-desktop-portal-gtk)
windowrule = center on, match:initial_class (xdg-desktop-portal-gtk)
