source = ~/.config/omarchy/current/theme/hyprlock.conf

$font = SF Pro Display
$font_regular = SF Pro Display
$font_bold = SF Pro Display Bold

general {
  grace = 1
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldDots, 1, 1, linear
}

label {
    monitor =
    text =   $USER
    color = rgba(255, 255, 255, 1)
    font_size = 15
    font_family = $font
    position = 0, 50
    halign = center
    valign = center
    zindex = 10
}

input-field {
    monitor =
    size = 650, 100
    position = 0, -50
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = $font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}

# Time
label {
    monitor =
    text = cmd[update:1000] date +"%-I:%M"
    color = rgba(255, 255, 255, 1)
    shadow_pass = 2
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2
    font_size = 100
    font_family = $font_bold
    position = 0, -100
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" | awk '{ for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }'
    color = rgba(255, 255, 255, 1)
    font_size = 24
    font_family = $font_bold
    position = 0, -270
    halign = center
    valign = top
}

# Random text
label {
    monitor =
    text = Time to live
    color = rgba(255, 255, 255, 1)
    font_size = 12
    font_family = $font
    position = -20, -20
    halign = right
    valign = top
}

source = ~/.local/state/omarchy/toggles/hyprlock.conf
